Jean/cow 367 deploy airdrop contract with erc20 permit
bleu/cow-airdrop-contract-deployer pull request #1
Opened 2024-09-10 18:36 UTC by JeanNeiverth

Fixed input csv: now only has two columns: address and airdrop amount
Fixed issue with merkleProof: removed everything related to encoding the airdrop type during the merkleProof generation
Moved processing data script to folder src/scripts
Created a README

2024-09-10 20:46 UTC, yvesfracari requested changes

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +Use this project to deploy your airdrop contracts.
I would add more details here, and explain that this interface is integrated with cow-swap hook store (add links)

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +- yarn
hardhat is installed by yarn, right? I think that we don't need this.

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +2. Move your "allocations.csv" file to /input-folder
Link to a mock version of this file containing the file structure.

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +3. Process files
What do "process files" mean? What it does? A description of this would be good.

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +- set tokenAddress to the contract address in the network you want to deploy of the token to be used
Ideally, this should be in an env file

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +- check needed .env keys in /hardhat.config.ts and declare them
`.env.example` file would be good for this

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +- change /hardhat.config.ts to support the network you want to deploy
Can't this be in a env as well?

2024-09-10 20:46 UTC, yvesfracari commented on README.md
> +npx hardhat ignition deploy ignition/modules/MerkleDistributor.ts --network <network> --deployment-id <optional_id_of_your_choice>
why do we need to set the network here and on the hardhat.config.ts?. Also, what is the `--deployment-id` option?

2024-09-10 20:46 UTC, yvesfracari commented on ignition/deployments/merkle1/artifacts/MerkleDModule#MerkleDistributor.dbg.json
👍

2024-09-10 20:46 UTC, yvesfracari commented on README.md
The steps described in this README include all that you have to know to deploy the contract. However, I think that we could include all the instructions that the user might need to know to deploy an airdrop that is integrated with our interface. This would include:
- Description of our interface and why to use it.
- Description of the git workflow to have it integrated with our requests (fork this repo, commit certain files, don't change its structure, etc).

2024-09-10 20:46 UTC, yvesfracari commented on index.js
👌

2024-09-10 20:46 UTC, yvesfracari commented on input-folder/allocations.csv
I would prefer to have an `example` branch with this and the generated json files.

2024-09-10 20:46 UTC, yvesfracari commented on src/scripts/processAllocations.ts
This could be inside `ts` folder, no?

2024-09-10 20:46 UTC, yvesfracari commented on src/scripts/processAllocations.ts
> +const outputFolder = "./mock-airdrop-data";
Could be on env or script inputs

2024-09-10 20:46 UTC, yvesfracari commented on src/scripts/processAllocations.ts
>    console.log("Generating Merkle proofs...");
```suggestion
  console.log("Input file processed. Generating Merkle proofs...");
```

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/claim.ts
> +//   .filter((c) => !isNaN(c));
👀

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/claim.ts
> +        [index, account, claimableAmount]
👍

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/claim.ts
>    "claimedAmount",
Do we still have the `claimedAmount` ?

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/csv.ts
> +    //}
👀

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/split.ts
> +  claims: ProvenClaim[]
take care on style diffs. Don't need to fix it here if it is too hard, but take care on next PRs 😃

2024-09-10 20:46 UTC, yvesfracari commented on src/ts/split.ts
> +  desiredCohortSize = 70
just out of curiosity, do you know what is this?

2024-09-11 17:48 UTC, jean-neiverth commented on README.md
> +- yarn
I don't know exactly how this works, but the command lines used in terminal  are "npx hardhat ...something", so I guess hardhat must be installed in your environment out of yarn, right?

2024-09-11 17:51 UTC, jean-neiverth commented on src/ts/claim.ts
>    "claimedAmount",
The code is still searching for it in the .csv, but it is not used to compute merkleProof

2024-09-11 17:53 UTC, jean-neiverth commented on src/ts/split.ts
> +  desiredCohortSize = 70
No, I don't

2024-09-11 18:37 UTC, jean-neiverth commented on README.md
> +- change /hardhat.config.ts to support the network you want to deploy
The idea here is to say that the user must fill these informations in the .env file, maybe I can explicit more this

2024-09-11 18:46 UTC, jean-neiverth commented on README.md
> +npx hardhat ignition deploy ignition/modules/MerkleDistributor.ts --network <network> --deployment-id <optional_id_of_your_choice>
About the deployment settings: I didn't notice that it works event if we don't pass the --network parameter. I think I will remove this then.

About the deployment id: it is just an optional parameter to make it easier to verify the contract later. I will explicit this.

2024-09-11 18:56 UTC, jean-neiverth commented on src/scripts/processAllocations.ts
I think its good to have this script in a separate folder, so we can check it is the "father" that calls the others

2024-09-12 12:23 UTC, yvesfracari approved these changes
Looking good, thanks for working on the review comments! Just let one comment about separating our implementation from the repo main branch. IMO the main branch should be the raw state of the repo and we should create an `example` branch with our implementation / use case. wdyt?

2024-09-12 12:23 UTC, yvesfracari commented on mock-airdrop-data/chunks/0x000000000000541e251335090ac5b47176af4f7e.json
I would prefer to move these files to a new branch, is that possible? I would like an `example` branch

2024-09-12 18:44 UTC, merged